replicaCount: 2
image:
  repository: ghcr.io/protikpatra/production-devops-platform
  tag: 7617b4f383774987bb8047413769948c5a2da5fe
  pullPolicy: Always
database:
  host: postgres-service
  name: orders_db
  user: postgres
  password: SuperSecretPassword123!
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
autoscaling:
  enabled: false