apiVersion: v1
kind: ConfigMap
metadata:
  name: order-api-config
data:
  DB_HOST: "postgres-service"
  DB_NAME: "orders_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: order-api-secret
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "SuperSecretPassword123!"